# Generated by Django 6.0.3 on 2026-03-06 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FloorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('badge_id', models.CharField(max_length=50)),
                ('badge_type', models.CharField(blank=True, max_length=100)),
                ('floor', models.CharField(max_length=100)),
                ('project', models.CharField(blank=True, max_length=255)),
                ('mail_subject', models.CharField(blank=True, max_length=255)),
                ('mail_entry_id', models.CharField(max_length=255, unique=True)),
                ('request_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
