# Generated by Django 6.0.3 on 2026-03-06 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='floorrequest',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
