# Generated by Django 6.0.3 on 2026-03-07 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0002_floorrequest_is_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='floorrequest',
            name='mail_received_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
